library(amap)
hc = hcluster(USArrests,method = "euclidean", link="single")
png("p22_ex_out/USArrests-single.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()
hc = hcluster(USArrests,method = "euclidean", link="average")
png("p22_ex_out/USArrests-average.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()

x = iris[,1:4]
hc = hcluster(x,method = "euclidean", link="single")
png("p22_ex_out/per-iris-single.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()
hc = hcluster(x,method = "euclidean", link="average")
png("p22_ex_out/per-iris-average.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()
hc = hcluster(x,method = "euclidean", link="complete")
png("p22_ex_out/per-iris-complete.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()

hc = hcluster(t(x),method = "euclidean", link="single")#t()轉移矩陣
png("p22_ex_out/type-iris-single.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()
hc = hcluster(t(x),method = "euclidean", link="average")
png("p22_ex_out/type-iris-average.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()
hc = hcluster(t(x),method = "euclidean", link="complete")
png("p22_ex_out/type-iris-complete.png",width = 10,height = 5,res = 300,units="in")
plot(hc)
dev.off()